In [1]:
# импорты 
import numpy as np

In [42]:
# Примеры создания массивов
# одномерные массивы
a = np.array([1,2,3,4,5])
b = np.zeros(2)
c = np.ones(2)
d = np.eye(3).flatten() # лазутчик)
a, b, c, d

(array([1, 2, 3, 4, 5]),
 array([0., 0.]),
 array([1., 1.]),
 array([1., 0., 0., 0., 1., 0., 0., 0., 1.]))

In [43]:
# Убедимся, что тип ndarray
type(a), type(b), type(c), type(d)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [44]:
# и в размерности
a.shape, b.shape, c.shape, d.shape

((5,), (2,), (2,), (9,))

In [45]:
# Примеры двумерных массивов
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.zeros((3,3))
c = np.ones((3,3))
d = np.eye(4)
# размерность
print(a.shape, b.shape, c.shape, d.shape)
a, b, c, d

(3, 3) (3, 3) (3, 3) (4, 4)


(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [46]:
# Примеры получения отдельного элемента
# элемент 3х3
print(a[2, 2])
# элемент 1х3
print(a[0, 2])
# столбец 2
print(a[:, 1])
# первые 2 строки
print(a[0:2, :])
# cnjk,ws
print(d[0:3, 0:2])


9
3
[2 5 8]
[[1 2 3]
 [4 5 6]]
[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [ ]:
# Вектоные операции
a = np.array([1, 2, 3])
b = np.array([-1, -2, -3])
# результаты поэлементного сложения, вычитания, умножения
print(a+b)
print(a-b)
print(a*b)
# для мартриц
a = np.array([[1, 2, 3], [1, 2, 3]])
b = np.array([[-1, -2, -3], [-1, -2, -3]])
print(a+b)
print(a-b)
print(a*b)
print(b.T)
print(a@b.T)
print(a.T@b)


[0 0 0]
[2 4 6]
[-1 -4 -9]
[[0 0 0]
 [0 0 0]]
[[2 4 6]
 [2 4 6]]
[[-1 -4 -9]
 [-1 -4 -9]]
[[-1 -1]
 [-2 -2]
 [-3 -3]]
[[-14 -14]
 [-14 -14]]
[[ -2  -4  -6]
 [ -4  -8 -12]
 [ -6 -12 -18]]


In [ ]:
# статистика
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
# мат ожидание или среднее
print(a.mean(axis=0), a.mean(axis=1))
# сумма
print(a.sum(axis=0), a.sum(axis=1))
# макс и мин
print(a.max(axis=0), a.min(axis=1))

[[1 2 3]
 [4 5 6]]
[2.5 3.5 4.5] [2. 5.]
[5 7 9] [ 6 15]
[4 5 6] [1 4]
